import { Inter } from 'next/font/google'
import '../styles/globals.css'
import '@fontsource/roboto-mono';
import '@fontsource/jetbrains-mono'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
